name: Deploy to Play Store
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: 'Fastlane lane to use (beta OR promote_to_production OR production)'
        required: true
        default: 'beta'
  # Refs/tags push events to matching v*, i.e. v1.0, v20.15.10
  push:
    tags:
    - 'v*'
jobs:
  get-commit-sha:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $(git rev-parse --short "$GITHUB_SHA")
          echo $(git rev-parse --short HEAD)
