name: Deploy to Play Store
on: workflow_dispatch
jobs:
  get-commit-sha:
    name: Get GIT commit sha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          ref: ${{github.ref}}
      - name: "Echo commit sha"
        run: |
          echo $(git rev-parse --short "$GITHUB_SHA")
          echo $(github.ref)
