name: Deploy to Play Store
on: workflow_dispatch
jobs:
  get-commit-sha:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $(git rev-parse --short "$GITHUB_SHA")
          echo $(git rev-parse --short HEAD)
