name: Appium Integration Test Demo
on: [push, pull_request]
jobs:
  build-ipa:
    runs-on: macos-latest
    outputs:
      browserstack_app_url: ${{ steps.upload.outputs.app_url }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build ipa
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - run: flutter --version
      - run: flutter build ios --release --no-codesign
      - run: mkdir Payload
      - run: cp -r build/ios/iphoneos/Runner.app Payload/
      - run: zip -r MyApp.ipa Payload/
      - id: upload
        name: Upload app to BrowserStack
        run: |
          app_url=$(curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@${PWD}/MyApp.ipa" | jq '.app_url')
          echo "::set-output name=app_url::${app_url}"
  run-integration-test:
    runs-on: ubuntu-latest
    needs: build-ipa
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_APP_ID: ${{ needs.build-ipa.outputs.browserstack_app_url }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          cd appium
          npm i
          node index.js



        
