name: Appium Integration Test Demo
on: [push, pull_request]
jobs:
  Build ipa:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build ipa
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - run: flutter --version
      - run: flutter build ios --release --no-codesign
      - run: mkdir MyApp
      - run: cp -r build/ios/iphoneos/Runner.app MyApp/
      - run: zip -r MyApp.ipa MyApp/
      - run: ls

        
