name: Appium Integration Test Demo
on: [push, pull_request]
jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build ipa
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - run: flutter --version
      - run: flutter build ios --release --no-codesign
      - run: mkdir Payload
      - run: cp -r build/ios/iphoneos/Runner.app Payload/
      - run: zip -r MyApp.ipa Payload/
      - name: Upload app to BrowserStack
        run: curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@${PWD}/MyApp.ipa"

        
